name: Build and Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  UnitTests: '$(System.DefaultWorkingDirectory)/NotificationAPI.UnitTests/NotificationAPI.UnitTests.csproj'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Unit Test UnitTests
      run: dotnet test $(UnitTests) --no-build --verbosity normal
    
